import { ReactNode } from 'react';
// import '@/styles/globals.css'
import '../styles/dist.css';
import styles from '../styles/Home.module.css';

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div data-theme="synthwave" className={styles.container}>
          <div className="navbar bg-base-100">
            <div className="flex-1">
              <a className="btn-ghost btn text-xl normal-case">
                Vaporwave Aesthetic React-Three/Fiber Demo
              </a>
            </div>
          </div>
          <main className={styles.main}>{children}</main>
          <footer className={styles.footer}>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{' '}
            </a>
          </footer>
        </div>
      </body>
    </html>
  );
}